import { LDProvider } from 'launchdarkly-react-client-sdk';  // Correct import
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sdkKey = process.env.LD_SDK_KEY || '';  // Accessing the correct environment variable

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrapping the children with LDProvider to enable feature flagging */}
        <LDProvider clientSideID={sdkKey}>
          {children}
        </LDProvider>
      </body>
    </html>
  );
}
